-- Справочники
CREATE TABLE IF NOT EXISTS genres (
  genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpaRating (
  mpaRating_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

--CREATE TABLE IF NOT EXISTS friendshipStatus (
--  friendshipStatus_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  statusName VARCHAR(255) NOT NULL
--);

-- Основные сущности
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  login VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  birthday DATE
);

CREATE TABLE IF NOT EXISTS films (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  releaseDate DATE,
  duration INT,
  mpaRating_id INT,
  FOREIGN KEY (mpaRating_id) REFERENCES mpaRating (mpaRating_id)
);

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    useful_rating INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (film_id) REFERENCES films (id)
);

CREATE TABLE IF NOT EXISTS user_feeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_type VARCHAR(10) NOT NULL CHECK (event_type IN ('LIKE', 'REVIEW', 'FRIEND')),
    operation VARCHAR(10) NOT NULL CHECK (operation IN ('ADD', 'REMOVE', 'UPDATE')),
    entity_id BIGINT NOT NULL,
    timestamp BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
-- Связывающие таблицы
CREATE TABLE IF NOT EXISTS review_ratings (
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating_type VARCHAR(10) NOT NULL CHECK (rating_type IN ('LIKE', 'DISLIKE')),
    rated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (review_id, user_id),
    FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friendList (
  user_id BIGINT NOT NULL,
  friend_id BIGINT NOT NULL,
--  friendshipStatus_id INT,
  PRIMARY KEY(user_id,friend_id),
  FOREIGN KEY (user_id) REFERENCES users (id),
  FOREIGN KEY (friend_id) REFERENCES users (id)
--  FOREIGN KEY (friendshipStatus_id) REFERENCES friendshipStatus (friendshipStatus_id)
);

CREATE TABLE IF NOT EXISTS likes (
  film_id BIGINT,
  user_id BIGINT,
  PRIMARY KEY (user_id, film_id),
  FOREIGN KEY (film_id) REFERENCES films (id),
  FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id BIGINT,
  genre_id INT,
  PRIMARY KEY (film_id, genre_id),
  FOREIGN KEY (film_id) REFERENCES films (id),
  FOREIGN KEY (genre_id) REFERENCES genres (genre_id)
);

CREATE TABLE IF NOT EXISTS directors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_directors (
  film_id BIGINT NOT NULL,
  director_id BIGINT NOT NULL,
  PRIMARY KEY (film_id, director_id),
  FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
  FOREIGN KEY (director_id) REFERENCES directors (id) ON DELETE CASCADE
);
