-- Справочники
CREATE TABLE IF NOT EXISTS genres (
  genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpaRating (
  mpaRating_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS friendshipStatus (
  friendshipStatus_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  statusName VARCHAR(255) NOT NULL
);

-- Основные сущности
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  login VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  birthday DATE
);

CREATE TABLE IF NOT EXISTS films (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  releaseDate DATE,
  duration INT,
  mpaRating_id INT,
  FOREIGN KEY (mpaRating_id) REFERENCES mpaRating (mpaRating_id)
);

-- Связывающие таблицы
CREATE TABLE IF NOT EXISTS friendList (
  user_id BIGINT,
  friend_id BIGINT,
  friendshipStatus_id INT,
  PRIMARY KEY(user_id,friend_id),
  FOREIGN KEY (user_id) REFERENCES users (id),
  FOREIGN KEY (friend_id) REFERENCES users (id),
  FOREIGN KEY (friendshipStatus_id) REFERENCES friendshipStatus (friendshipStatus_id)
);

CREATE TABLE IF NOT EXISTS likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id BIGINT,
  user_id BIGINT,
  FOREIGN KEY (film_id) REFERENCES films (id),
  FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS film_genres (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id BIGINT,
  genre_id INT,
  FOREIGN KEY (film_id) REFERENCES films (id),
  FOREIGN KEY (genre_id) REFERENCES genres (genre_id)
);
